base: 1
deletion: 0.5

extensions:
  go:  1
  sum: 0.1
  mod: 0.5
  sh: 1.5
  yml:  2
  yaml: 2
  json: 2
  md: 0.2

labels:
  - name: "> 60 min"
    time: 3600

  - name: "30-60 min"
    time: 1800

  - name: "15-30 min"
    time: 900

  - name: "10-15 min"
    time: 600

  - name: "5-10 min"
    time: 300

  - name: "1-5 min"
    time: 60

  - name: "< 1 min"
    time: 0
