name: Test and coverage

on:
  push:
    paths:
      - '**.go'
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: go get
        run: go get ./...

      - name: go mod tidy
        run: go mod tidy

      - name: Run tests
        run: make test
